services:
  essay-app:
    build: .
    container_name: aes_ielts
    ports:
      - "8000:8000"
    runtime: nvidia
    environment:
      - PYTHONPATH=/app
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/aes
      SECRET_KEY: "supersecretkey"
      ALGORITHM: "HS256"
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aes
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: